export { default as Button } from "./Button";
export { default as BackgroundHeart } from "./BackgroundHeart";
export { default as WhiteBox } from "./WhiteBox";
export { default as IdInput } from "./IdInput";
export { default as InputWithLabel } from "./InputWithLabel";
export { default as AuthTimer } from "./AuthTimer";
export { default as CaptchaWithButton } from "./CaptchaWithButton";
export { default as PasswordInput } from "./PasswordInput";
export { default as SwitchButton } from "./SwitchButton";
