name: ON PR/Merge - Check Errors | Build

on:
  pull_request:
    branches: [ "develop", "main" ]
    types: [ "opened", "closed" ]
  push:
    branches: [ "develop", "main" ]

jobs:
  merged:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    name: Build Nextjs
    uses: ./.github/workflows/front.yml
    secrets:
      ECR_REPO_DEV_FRONT: ${{ secrets.ECR_REPO_DEV_FRONT }}
      OIDC_ROLE: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
      AWS_DEPLOY_APP_NAME: ${{ secrets.AWS_DEPLOY_APP_NAME }}
      AWS_DEPLOY_GROUP: ${{ secrets.AWS_DEPLOY_GROUP }}
      AWS_DEPLOY_CONFIG: ${{ secrets.AWS_DEPLOY_CONFIG }}

  pr:
    if: ${{ github.event.pull_request.merged == false && github.event != 'push'}}
    name: Error Check
    uses: ./.github/workflows/check_err.yml

  pushed-1:
    if: ${{ github.event.pull_request.merged == false && github.event == 'push'}}
    name: Error Check
    uses: ./.github/workflows/check_err.yml

  pushed-2:
    if: ${{ github.event.pull_request.merged == false && github.event == 'push'}}
    name: Build Nextjs
    uses: ./.github/workflows/front.yml
    secrets:
      ECR_REPO_DEV_FRONT: ${{ secrets.ECR_REPO_DEV_FRONT }}
      OIDC_ROLE: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
      AWS_DEPLOY_APP_NAME: ${{ secrets.AWS_DEPLOY_APP_NAME }}
      AWS_DEPLOY_GROUP: ${{ secrets.AWS_DEPLOY_GROUP }}
      AWS_DEPLOY_CONFIG: ${{ secrets.AWS_DEPLOY_CONFIG }}
    needs: pushed-1